# Generated by Django 2.0.3 on 2018-03-27 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cafe_name', models.CharField(default='', max_length=30)),
                ('menu', models.CharField(default='', max_length=100)),
                ('is_new', models.BooleanField(default=False)),
            ],
        ),
    ]
