# Generated by Django 2.0.3 on 2018-03-27 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hkuhaksik', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KyoMenu',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cafe_name', models.CharField(default='', max_length=30)),
                ('menu', models.CharField(default='', max_length=100)),
                ('is_new', models.BooleanField(default=False)),
            ],
        ),
        migrations.RenameModel(
            old_name='Menu',
            new_name='HakMenu',
        ),
    ]
